apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  namespace: apps
  labels:
    app: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
      - name: notifications-api
        image: saarwasserman/dinghy-notifications-api:0.1.0
        imagePullPolicy: Always
        command: 
          - ./bin/api
          - -port=40010
          - -kafka-host=my-cluster-kafka-bootstrap.kafka.svc.cluster.local
          - -kafka-port=9092
        ports:
        - containerPort: 40010
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
          requests:
            ephemeral-storage: "1Gi"
            cpu: "500m"
            memory: "250Mi"
          
